### PR TITLE
Added support for cross arch builds & network inside mock

### PR DESCRIPTION
**Pull request by k0ste**
* cross arch builds: now container can build x86 packages at ARM platform
* network support inside mock chroot: now possible build golang applications (https://github.com/rpm-software-management/mock/issues/919)

### CODE REVIEW

**Review by mmornati — APPROVED** [review]
❤️ Thanks for this PR!

**Comment by waja** [comment]
Is there a docu how to crossbuild packages with this change?

**Comment by k0ste** [comment]
> Is there a docu how to crossbuild packages with this change?

Definitely, just add `MOCK_CONFIG` to your build, for example if your platform is ARM, but you need packages for x86, the config will be `MOCK_CONFIG="centos-stream-8-x86_64"`

**Comment by waja** [comment]
I turned it around, my platform is x86 and I added "alma+epel-9-aarch64" as mock config but got allover the places "error: failed to exec scriptlet interpreter /bin/sh: Exec format error" which seems like an indicator that the arch is not matching.

**Comment by k0ste** [comment]
> I turned it around, my platform is x86 and I added "alma+epel-9-aarch64" as mock config but got allover the places "error: failed to exec scriptlet interpreter /bin/sh: Exec format error" which seems like an indicator that the arch is not matching.

Please, open new issue with full command's and container logs, for this. This is closed PR 🙂

**Pull request merged**
